### PR TITLE
Added SavedState to the menu

### PR DESCRIPTION
**Pull request by leonardo2204**
Added SavedState feature to the menu
e.g. on rotation, if the menu was open, when rotated the menu will be shown automagically.

### CODE REVIEW

**Comment by leonardo2204** [comment]
Is there any issue with this pull ?

**Review by yavski — APPROVED** [review]
Sorry for responding so late, your work seems ok, thanks for the contribution.

**Comment by leonardo2204** [comment]
@yavski I was thinking about adding an option wheter to show or not the menu on rotation, what do you think about that ?

**Comment by yavski** [comment]
It would be inconsistent with the overflow menu, or the navigation view. The speed dial menu is just another way of presenting a menu resource, I don't see a reason why it should be inconsistent.

**Comment by leonardo2204** [comment]
Yeah, agree with you.

Ok then, thank you !

---

De: Yavor Ivanov notifications@github.com
Enviado: segunda-feira, 17 de outubro de 2016 05:54:03
Para: yavski/fab-speed-dial
Cc: Leonardo Ferrari; Author
Assunto: Re: [yavski/fab-speed-dial] Added SavedState to the menu (#23)

It would be inconsistent with the overflow menu, or the navigation view. The speed dial menu is just another way of presenting a menu resource, I don't see a reason why it should be inconsistent.

##

**Pull request merged**
