### PR TITLE
Added multi-color menu item feature

### PR DESCRIPTION
**Pull request by alanjcaceres**
Added an attribute that will allow use of multiple colors for the fab menu.
It colors each mini fab by taking into consideration the menu order of each item.
You need to provide an integer-array resource that contains the colors you want for each item.

### CODE REVIEW

**Comment by bottle-rocket-11** [comment]
Looking forward to having this merged ;)

**Review by yavski — APPROVED** [review]
Good job, thanks for your contribution! Next time don't add the changes to your README.md to the PR please.

**Comment by bottle-rocket-11** [comment]
Thank you @yavski @alanjcaceres you guys rock my socks right off.  So excited

**Comment by santafebound** [comment]
How do you actually use this feature? I have:

```
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item
        android:id="@+id/action_call"
        android:icon="@drawable/ic_menu"
        android:orderInCategory="0"
        android:title="Test" />
    <item
        android:id="@+id/action_text"
        android:icon="@drawable/ic_menu"
        android:orderInCategory="1"
        android:title="Test" />
    <item
        android:id="@+id/action_email"
        android:icon="@drawable/ic_menu"
        android:orderInCategory="2"
        android:title="Test" />
</menu>
```

and...

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer-array name="fab_menu_item_colors">
        <!-- A dark Holo shade of red -->
        <item>@color/primary</item>
        <!-- A Holo shade of purple -->
        <item>@color/primary_dark</item>
        <!-- A light Holo shade of green -->
        <item>@color/primary_darker</item>
    </integer-array>
</resources>
```

**Comment by alanjcaceres** [comment]
You need to reference the array in the FabSpeedDial in your layout xml
app:miniFabBackgroundTintList="@array/fab_menu_colors"

**Pull request merged**
